/**
 * Integration tests: cli/commands/logs.ts parseLine() container format branch
 * — no Docker required.
 *
 * The CLI logs command uses its own parseLine() function to parse log file entries.
 * This function has a branch for container-format logs:
 *
 *   if (obj._log && typeof obj.level === "string") {
 *     // Container format: { _log: true, level: "info", msg: "...", ts: 1234 }
 *     const { _log, level: levelStr, ts, ...rest } = obj;
 *     return { ...rest, level: LEVEL_NAME_TO_NUM[levelStr] ?? 30, time: ts ?? Date.now() };
 *   }
 *
 * This branch normalizes container-format log entries (generated by Docker containers)
 * into the standard pino format used by the CLI formatter. Key behaviors:
 *   - _log field is stripped
 *   - level string ("info", "warn", etc.) mapped to numeric (30, 40, etc.)
 *   - ts renamed to time
 *   - Defaults to level=30 for unknown level strings
 *   - Defaults to Date.now() if ts is missing
 *
 * Test scenarios:
 *   1. Container format info entry → displayed as normal entry (level 30)
 *   2. Container format warn entry → displayed as WARN (level 40)
 *   3. Container format error entry → displayed as ERROR (level 50)
 *   4. Container format with unknown level string → defaults to level 30 (info)
 *   5. Container format with missing ts → time defaults gracefully (no crash)
 *   6. Mix of container-format and pino-format entries → both displayed
 *
 * Covers:
 *   - cli/commands/logs.ts: parseLine() container format branch
 *     (obj._log && typeof obj.level === "string" → levelMap lookup + ts → time rename)
 *   - cli/commands/logs.ts: parseLine() unknown level → LEVEL_NAME_TO_NUM fallback (30)
 *   - cli/commands/logs.ts: parseLine() missing ts → time defaults to Date.now()
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";

const { execute: logsExecute } = await import(
  /* @vite-ignore */
  "/tmp/repo/packages/action-llama/dist/cli/commands/logs.js"
);

/** Capture console.log and console.error output during a callback. */
async function captureOutput(fn: () => Promise<void>): Promise<{ logs: string[]; errors: string[] }> {
  const logs: string[] = [];
  const errors: string[] = [];
  const origLog = console.log;
  const origError = console.error;
  console.log = (...args: any[]) => logs.push(args.join(" "));
  console.error = (...args: any[]) => errors.push(args.join(" "));
  try {
    await fn();
  } finally {
    console.log = origLog;
    console.error = origError;
  }
  return { logs, errors };
}

/** Get today's date in YYYY-MM-DD format. */
function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Build a container-format log line (as Docker containers emit). */
function containerLine(level: string, msg: string, extras?: Record<string, unknown>): string {
  return JSON.stringify({
    _log: true,
    level,
    msg,
    ts: Date.now(),
    ...extras,
  });
}

/** Build a pino-format log line. */
function pinoLine(msg: string, level = 30): string {
  return JSON.stringify({ level, time: Date.now(), msg });
}

/** Set up a minimal project with a log file for an agent. */
function setupProjectWithLogs(projectDir: string, agentName: string, logLines: string[]): void {
  const logsDir = join(projectDir, ".al", "logs");
  mkdirSync(logsDir, { recursive: true });
  writeFileSync(
    join(projectDir, "config.toml"),
    '[models.sonnet]\nprovider = "anthropic"\nmodel = "claude-3-5-sonnet-20241022"\nauthType = "api_key"\n'
  );
  const logFile = join(logsDir, `${agentName}-${today()}.log`);
  writeFileSync(logFile, logLines.join("\n") + "\n");
}

describe(
  "integration: cli/commands/logs.ts parseLine() container format branch (no Docker required)",
  { timeout: 30_000 },
  () => {
    let projectDir: string;

    beforeEach(() => {
      projectDir = mkdtempSync(join(tmpdir(), "al-logs-container-fmt-test-"));
    });

    afterEach(() => {
      rmSync(projectDir, { recursive: true, force: true });
    });

    // ── Container format info entry ──────────────────────────────────────────

    it("container-format info entry is displayed as a normal entry", async () => {
      const lines = [
        containerLine("info", "agent completed task"),
      ];
      setupProjectWithLogs(projectDir, "container-info-agent", lines);

      const { logs } = await captureOutput(() =>
        logsExecute("container-info-agent", { project: projectDir, lines: "100" })
      );

      const output = logs.join("\n");
      // Should display the message without errors
      expect(output).toContain("agent completed task");
    });

    // ── Container format warn entry ──────────────────────────────────────────

    it("container-format warn entry is displayed as WARN", async () => {
      const lines = [
        containerLine("warn", "something looks wrong"),
      ];
      setupProjectWithLogs(projectDir, "container-warn-agent", lines);

      const { logs } = await captureOutput(() =>
        logsExecute("container-warn-agent", { project: projectDir, lines: "100" })
      );

      const output = logs.join("\n");
      expect(output).toContain("WARN");
      expect(output).toContain("something looks wrong");
    });

    // ── Container format error entry ─────────────────────────────────────────

    it("container-format error entry is displayed as ERROR", async () => {
      const lines = [
        containerLine("error", "fatal error occurred"),
      ];
      setupProjectWithLogs(projectDir, "container-error-agent", lines);

      const { logs } = await captureOutput(() =>
        logsExecute("container-error-agent", { project: projectDir, lines: "100" })
      );

      const output = logs.join("\n");
      expect(output).toContain("ERROR");
      expect(output).toContain("fatal error occurred");
    });

    // ── Container format unknown level → defaults to 30 (info) ───────────────

    it("container-format entry with unknown level string defaults to level 30 (info)", async () => {
      const lines = [
        containerLine("verbose", "some verbose message"),
      ];
      setupProjectWithLogs(projectDir, "container-unknown-level-agent", lines);

      // Should not crash - defaults to 30 (info)
      const { logs, errors } = await captureOutput(() =>
        logsExecute("container-unknown-level-agent", { project: projectDir, lines: "100" })
      );

      // No error should be thrown
      expect(errors.filter((e) => e.includes("Error") || e.includes("crash")).length).toBe(0);
      // Message should appear (info level is shown by default)
      expect(logs.join("\n")).toContain("some verbose message");
    });

    // ── Container format missing ts → no crash ───────────────────────────────

    it("container-format entry without ts field does not crash", async () => {
      // No ts field → time defaults to Date.now()
      const lines = [
        JSON.stringify({ _log: true, level: "info", msg: "no timestamp entry" }),
      ];
      setupProjectWithLogs(projectDir, "container-no-ts-agent", lines);

      const { errors } = await captureOutput(() =>
        logsExecute("container-no-ts-agent", { project: projectDir, lines: "100" })
      );

      // No error should be thrown for missing ts
      expect(errors.filter((e) => e.includes("TypeError") || e.includes("crash")).length).toBe(0);
    });

    // ── Mixed container and pino format entries ──────────────────────────────

    it("mix of container-format and pino-format entries both displayed correctly", async () => {
      const lines = [
        pinoLine("pino format message"),
        containerLine("info", "container format message"),
      ];
      setupProjectWithLogs(projectDir, "mixed-format-agent", lines);

      const { logs } = await captureOutput(() =>
        logsExecute("mixed-format-agent", { project: projectDir, lines: "100" })
      );

      const output = logs.join("\n");
      expect(output).toContain("pino format message");
      expect(output).toContain("container format message");
    });
  },
);
